targets = ["//:conversion"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
version = "1.63.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.63.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
version = "1.63.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-typeof"
version = "1.63.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
version = "1.63.0"