manifest = "ae70b6505baa23cc66ffac0eff38f51478c831bcaa61604576ed3253d6118451"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-typeof"
target = "//:typeof"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.55.0" ]
revision = "892598f066f15a4b8352bbd6b5f2b1a90e12e6fc"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.55.0" ]
revision = "8fe65abe2334e0d84c2cba4c768ec2f2360b33e1"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.55.0" ]
revision = "8dcbb4d4610e05a948704c47898a34c4fee827cb"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.55.0" ]
revision = "a41bc5546421204bda9a1572a75474b7197559b2"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.55.0" ]
revision = "e53e7e72e660990dcc5c6c015d724fab0c4516a6"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "1.55.0" ]
revision = "8acd00708b85fac33a24944037893b92b360783c"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.55.0" ]
revision = "59b48f8ac824d7985183ffb3c3174c8caebfef20"
