targets = ["//:conversion"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-typeof"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
version = "1.44.0"