manifest = "4211659c9016fe305740300a0ee1c198ba5c9a641d62ec9ed1992df79991a751"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
target = "//:throw_exception"

[[dependency]]
package = "github.com/buckaroo-pm/boost-typeof"
target = "//:typeof"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.57.0" ]
revision = "e4476f3159e98aebaa3a057bd2670653cb778d48"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.57.0" ]
revision = "ee7d5652f970bde066501c7cee1d0d2ad43c2348"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.57.0" ]
revision = "9194d8422e508b914041aad8c97a55b712cf4855"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.57.0" ]
revision = "08aef274380d048f40aea0f40be03d3c943c0917"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.57.0" ]
revision = "2d919cee0368f6dcef90b5010755588defadeb5e"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.57.0" ]
revision = "11c429d65c6cea226770f7abf7b4af91419af893"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.57.0" ]
revision = "701273f2c2f1da1f06a00b11ee15f30a358a775c"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.57.0" ]
revision = "7e886911750f84477833ba575aa654092c553cd4"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.57.0" ]
revision = "b71c8285ba07563884f165ae769db3cd5a5dc45a"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "1.57.0" ]
revision = "9a83b25172a84326263a7236784ed16a6df2ea6d"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.57.0" ]
revision = "672b552c874c72529564a79448c4b48b966ba7c5"
